# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TerraQgis
                                 A QGIS plugin
 TerraQgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-09
        copyright            : (C) 2024 by Furinets O
        email                : some@some.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TerraQgis class from file TerraQgis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .terra_qgis import TerraQgis
    return TerraQgis(iface)
